### ISSUE TITLE
プロフィール入力ページを作成

### ISSUE THREAD

**Issue by sueCalystegia00** [ExpectBonus/doko-yahoo#12]
# ページレイアウト
- [ ] Vue: pages/profile.vue 作成

# 入力項目
- [ ] ユーザ名: 文字列入力
- [ ] 趣味: ラジオボタンっぽいチェックボタン
- [ ] 採用職種: エンジニア、デザイナー、ビジネスの選択式(radio)
- [ ] 出身地: 都道府県47ヶ所、北から順に選択式(radio)
  - [都道府県json](https://qiita.com/isamusuzuki/items/d2f40b043ada0a106548)
- [ ] 希望地域: 都道府県47ヶ所、北から順に選択式(radio)
  - 第一希望（*必須）、第二希望（任意）、第三希望（任意）

**Comment by sueCalystegia00** [comment]
# プロトタイプ差育成
![profile入力完了](https://user-images.githubusercontent.com/52482280/174059254-14bb592a-fd27-429c-b28a-4754bfa17ca0.png)
![profile未入力状態](https://user-images.githubusercontent.com/52482280/174059260-83e31ea7-0ffd-48d4-bc9a-e47ecb351e59.png)

https://www.figma.com/file/b8GXxAbMNQY3ahgyN3wp1l/Doko-Yahoo?node-id=45%3A270

**Comment by sho-yoshikawa** [comment]
done?
